# Generated by Django 3.1 on 2020-08-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='movie_name',
            field=models.CharField(max_length=100),
        ),
    ]
